import { genId } from '@shared/ids'

/** Carousel page formats (Instagram). All coordinates in the project are
 *  normalized 0..1 so they are resolution-independent. */
export type Format = '4:5' | '1:1'
export const FORMATS: Record<Format, { w: number; h: number }> = {
  '4:5': { w: 1080, h: 1350 },
  '1:1': { w: 1080, h: 1080 }
}

/** A real photo of Elisa composited onto the slide (face stays identical). */
export interface PhotoLayer {
  id: string
  kind: 'photo'
  src: string // dataURL
  xFrac: number // center X (0..1)
  yFrac: number // center Y (0..1)
  heightFrac: number // displayed height as a fraction of canvas height
  rotation: number // degrees
  opacity: number // 0..1
  grayscale: boolean // B/W faded-background look
  flip: boolean // mirror horizontally
}

/** A text box. */
export interface TextLayer {
  id: string
  kind: 'text'
  text: string
  fontFamily: string
  fontSizeFrac: number // of canvas height
  color: string
  bold: boolean
  italic: boolean
  align: 'left' | 'center' | 'right'
  lineHeightMul: number
  xFrac: number // center X of the text box
  yFrac: number // center Y of the text box
  widthFrac: number // box width fraction (controls wrapping)
  opacity: number
  shadow: boolean
  uppercase: boolean
  highlight: boolean
  highlightColor: string
}

export type Layer = PhotoLayer | TextLayer

export interface Slide {
  id: string
  bg: string | null // background image dataURL (generated by GPT)
  bgColor: string // fallback / base color
  layers: Layer[]
}

export interface BriefMeta {
  tema?: string
  obiettivo?: string
  caption?: string
  hashtag?: string[]
  commentoFissato?: string | null
}

export interface CaroselloProject {
  format: Format
  slides: Slide[]
  meta?: BriefMeta
}

export function makeTextLayer(partial: Partial<TextLayer> = {}): TextLayer {
  return {
    id: genId('txt'),
    kind: 'text',
    text: 'Scrivi qui…',
    fontFamily: 'Arial, Helvetica, sans-serif',
    fontSizeFrac: 0.058,
    color: '#1a1a1a',
    bold: true,
    italic: false,
    align: 'left',
    lineHeightMul: 1.18,
    xFrac: 0.5,
    yFrac: 0.5,
    widthFrac: 0.82,
    opacity: 1,
    shadow: false,
    uppercase: false,
    highlight: false,
    highlightColor: '#ffffff',
    ...partial
  }
}

export function makePhotoLayer(src: string, partial: Partial<PhotoLayer> = {}): PhotoLayer {
  return {
    id: genId('photo'),
    kind: 'photo',
    src,
    xFrac: 0.72,
    yFrac: 0.6,
    heightFrac: 0.92,
    rotation: 0,
    opacity: 1,
    grayscale: false,
    flip: false,
    ...partial
  }
}

export function makeSlide(partial: Partial<Slide> = {}): Slide {
  return { id: genId('slide'), bg: null, bgColor: '#f3efe7', layers: [], ...partial }
}

export function emptyProject(format: Format = '4:5'): CaroselloProject {
  return { format, slides: [makeSlide()] }
}
